const $=s=>document.querySelector(s);
const DB_NAME='travel-tracker-db',STORE='trips';
const backgrounds={travel:{'travel-coast':'linear-gradient(145deg,#527d99 0%,#92c3d4 38%,#d8b777 39%,#36584a 100%)','travel-city':'linear-gradient(140deg,#162033,#4c6681 43%,#d3a66d 44%,#684f4d 100%)','travel-sunset':'linear-gradient(145deg,#43386f,#dd7f77 46%,#f1c684 65%,#426b77)'},hiking:{'hiking-forest':'linear-gradient(145deg,#183b2b,#52744c 48%,#b0a66b 49%,#314b35)','hiking-mountain':'linear-gradient(160deg,#72879a,#d6e0e4 43%,#6b7d66 44%,#334a37)','hiking-autumn':'linear-gradient(145deg,#5b3526,#a86638 45%,#c6a45b 46%,#43523b)'},birthday:{'birthday-balloons':"url('assets/birthday-prototype.png') center/cover",'birthday-confetti':'linear-gradient(135deg,#7543a3,#e878aa 42%,#f5ce6a 43%,#53a9aa)','birthday-night':'linear-gradient(135deg,#17152f,#463a83 42%,#b34970 70%,#e7a451)'}};
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function dbGet(id){const db=await openDB();return new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function formatDateTime(ts){if(!ts)return'';const d=new Date(ts);if(Number.isNaN(d.getTime()))return'';return `${d.toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'})} · ${d.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})} Uhr`}
function bgCss(t){return backgrounds[t.category]?.[t.background]||'#64748b'}
function syncViewport(){const h=window.visualViewport?.height||window.innerHeight;document.documentElement.style.setProperty('--viewer-height',`${h}px`);$('#viewer')?.style.setProperty('--vh',`${h}px`)}
let current=-1,slides=[];
function goTo(index){if(index<0||index>=slides.length)return;current=index;slides.forEach((s,i)=>{s.classList.toggle('current',i===index);s.classList.toggle('left',i<index);s.classList.toggle('right',i>index)})}
function render(t){const goals=(t.goals||[]).filter(g=>g.photo);document.title=`${t.title||'Reise'} · Travel Tracker`;const viewer=$('#viewer');viewer.style.background=bgCss(t);viewer.style.backgroundSize='cover';viewer.style.backgroundPosition='center';const who=(t.participants||[]).filter(Boolean).join(', ')||'uns';viewer.innerHTML=`<section class="intro" id="intro"><div class="welcome"><div class="eyebrow">TRAVEL TRACKER</div><h1>Willkommen auf der Reise von</h1><h2>${esc(who)}</h2><p>${esc(t.title||'Unsere Reise')}</p>${goals.length?'<button class="start-btn" id="startBtn" type="button">Reise ansehen →</button>':'<p>Keine Fotos vorhanden.</p>'}</div></section><section class="stage" id="stage"></section><div class="lightbox" id="lightbox"><button class="lightbox-close" id="lightboxClose" type="button" aria-label="Schließen">×</button><img id="lightboxImage" alt=""></div>`;
 const stage=$('#stage');
 goals.forEach((g,i)=>{const slide=document.createElement('section');slide.className='slide right';const place=g.place?.name?`<a class="place-chip" href="${esc(g.place.url||`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(g.place.name)}`)}" target="_blank" rel="noopener" title="In Google Maps öffnen">⌖ ${esc(g.place.name)}</a>`:'';const info=g.info?`<section class="info-panel"><p>${esc(g.info)}</p></section>`:'';slide.innerHTML=`<div class="slide-main"><div class="slide-shell"><header class="destination-title"><span>ZIEL ${i+1}</span><h2>${esc(g.name||`Ziel ${i+1}`)}</h2></header><article class="memory-card"><div class="photo-frame" role="button" tabindex="0"><img src="${g.photo}" alt="${esc(g.name||'Reisefoto')}">${place}</div><div class="date-row">${esc(formatDateTime(g.capturedAt))}</div></article>${info}</div></div><nav class="bottom-nav">${i>0?'<button class="nav prev" type="button" aria-label="Vorheriges Ziel">‹</button>':''}${i<goals.length-1?'<button class="nav next" type="button" aria-label="Nächstes Ziel">›</button>':''}</nav>`;stage.appendChild(slide)});
 slides=[...stage.querySelectorAll('.slide')];
 $('#startBtn')?.addEventListener('click',()=>{$('#intro').classList.add('hidden-left');goTo(0)});
 stage.addEventListener('click',e=>{if(e.target.closest('.prev'))goTo(current-1);if(e.target.closest('.next'))goTo(current+1);const pf=e.target.closest('.photo-frame');if(pf&&!e.target.closest('.place-chip'))openLightbox(pf.querySelector('img').src,pf.querySelector('img').alt)});
 stage.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.closest('.photo-frame')){e.preventDefault();const img=e.target.closest('.photo-frame').querySelector('img');openLightbox(img.src,img.alt)}});
 $('#lightboxClose').onclick=closeLightbox;$('#lightbox').addEventListener('click',e=>{if(e.target.id==='lightbox')closeLightbox()});
 let sx=null;stage.addEventListener('touchstart',e=>{sx=e.touches[0]?.clientX??null},{passive:true});stage.addEventListener('touchend',e=>{if(sx===null||current<0)return;const ex=e.changedTouches[0]?.clientX??sx,dx=ex-sx;sx=null;if(Math.abs(dx)<55)return;dx<0?goTo(current+1):goTo(current-1)},{passive:true});
}
function openLightbox(src,alt){$('#lightboxImage').src=src;$('#lightboxImage').alt=alt||'';$('#lightbox').classList.add('open')}
function closeLightbox(){$('#lightbox').classList.remove('open')}
window.addEventListener('keydown',e=>{if(e.key==='Escape')closeLightbox();if(current>=0&&e.key==='ArrowRight')goTo(current+1);if(current>=0&&e.key==='ArrowLeft')goTo(current-1)});
window.addEventListener('resize',syncViewport);window.visualViewport?.addEventListener('resize',syncViewport);syncViewport();
(async()=>{const id=new URLSearchParams(location.search).get('id');if(!id){$('#loading').textContent='Keine Reise-ID übergeben.';return}try{const t=await dbGet(id);if(!t){$('#loading').innerHTML='Diese Reise ist auf diesem Gerät nicht gespeichert.<br><small>Importiere sie zuerst im Travel Tracker.</small>';return}render(t);syncViewport()}catch(e){console.error(e);$('#loading').textContent='Die Reise konnte nicht geladen werden.'}})();
