(() => {
  'use strict';

  const Core = window.TravelTrackerCore;
  if (!Core) throw new Error('TravelTrackerCore wurde nicht geladen.');
  const { db, escapeHtml, formatDateTime, mapsCoordinatesUrl } = Core;
  const app = document.getElementById('viewerApp');
  const FONT_STACKS = Object.freeze({
    system:'Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif',
    serif:'Georgia,"Times New Roman",serif',
    rounded:'"Trebuchet MS","Arial Rounded MT Bold",Arial,sans-serif',
    hand:'"Segoe Print","Bradley Hand","Comic Sans MS",cursive',
    mono:'ui-monospace,SFMono-Regular,Menlo,Consolas,monospace'
  });
  const state={trip:null,goals:[],current:0,started:false,swipeStartX:null,swipeStartY:null};

  function setViewportSize(){const viewport=window.visualViewport;document.documentElement.style.setProperty('--viewport-h',`${Math.round(viewport?.height||window.innerHeight)}px`);document.documentElement.style.setProperty('--viewport-w',`${Math.round(viewport?.width||window.innerWidth)}px`);}
  function showError(message){app.style.removeProperty('--bg-image');app.innerHTML=`<section class="viewer-message"><div><strong>Reise konnte nicht geöffnet werden.</strong><p>${escapeHtml(message)}</p><p><a href="index.html">Zurück zu Travel Tracker</a></p></div></section>`;}
  async function loadTrip(){const embedded=document.getElementById('embeddedTripData');if(embedded){try{return JSON.parse(embedded.textContent);}catch{throw new Error('Die eingebetteten Reisedaten sind beschädigt.');}}const id=new URLSearchParams(location.search).get('id');if(!id)throw new Error('Es wurde keine Reise-ID übergeben.');const trip=await db.getTrip(id);if(!trip)throw new Error('Diese Reise ist in diesem Browser nicht gespeichert. Öffne sie auf dem Gerät, auf dem sie erstellt wurde.');return trip;}
  function backgroundValue(trip){return trip.customBackground?`url("${trip.customBackground}") center/cover no-repeat`:(trip.backgroundCss||'linear-gradient(135deg,#506780,#b19357)');}
  function fontStack(goal){return FONT_STACKS[goal?.fontKey]||FONT_STACKS.system;}
  function locationLink(goal){const data=goal?.location;if(!data)return'';const lat=Number(data.latitude),lng=Number(data.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lng))return'';const text=String(data.label||'Ort in Google Maps ansehen');return`<a class="location-chip" href="${escapeHtml(mapsCoordinatesUrl(lat,lng))}" target="_blank" rel="noopener noreferrer">${escapeHtml(text)}</a>`;}
  function renderDecorations(){const items=Array.isArray(state.trip?.decorations)?state.trip.decorations:[];if(!items.length)return'';return`<div class="viewer-decorations" aria-hidden="true">${items.map(item=>`<span style="left:${Number(item.x)||50}%;top:${Number(item.y)||50}%;font-size:${Math.max(18,Math.min(80,Number(item.size)||42))}px;transform:translate(-50%,-50%) rotate(${Number(item.rotation)||0}deg)">${escapeHtml(item.emoji||'⭐')}</span>`).join('')}</div>`;}
  function renderSlide(goal,index){const info=String(goal.info||'').trim(),date=formatDateTime(goal.capturedAt),location=locationLink(goal);return`<section class="slide" data-index="${index}"><header class="destination-title"><span>ZIEL ${index+1}</span><h2 style="color:${goal.titleColor||'#fff'};font-family:${fontStack(goal)}">${escapeHtml(goal.name||`Ziel ${index+1}`)}</h2></header><div class="slide-center"><div class="content-stack${info?' has-info':''}"><article class="memory-card"><div class="photo-wrap"><button class="photo-open" type="button" data-photo-index="${index}" aria-label="Foto vergrößern"><img src="${goal.photo}" alt="${escapeHtml(goal.name||`Ziel ${index+1}`)}"></button>${location}</div>${date?`<div class="date-row">${escapeHtml(date)}</div>`:''}</article>${info?`<section class="info-panel"><p style="color:${goal.infoColor||'#344054'}">${escapeHtml(info)}</p></section>`:''}</div></div><footer class="viewer-footer">Travel Tracker · Erinnerungen, die bleiben</footer><div class="route-flare" aria-hidden="true"></div></section>`;}
  function buildViewer(){state.goals=(state.trip.goals||[]).filter(goal=>goal?.photo);if(!state.goals.length){showError('Die Reise enthält noch keine Fotos.');return;}document.title=`${state.trip.title||'Reise'} · Travel Tracker`;app.style.setProperty('--bg-image',backgroundValue(state.trip));const people=(state.trip.participants||[]).filter(Boolean).join(', ')||'uns';app.innerHTML=`${renderDecorations()}<section class="intro-screen" id="introScreen"><div class="welcome"><div class="eyebrow">TRAVEL TRACKER</div><h1>Willkommen auf der Reise von</h1><h2>${escapeHtml(people)}</h2><p>${escapeHtml(state.trip.title||'Unsere Reise')}</p><button class="start-btn" id="startJourneyBtn" type="button">Reise ansehen →</button></div></section><section class="journey-screen" id="journeyScreen"><div class="slider-viewport" id="sliderViewport"><div class="slider-track" id="sliderTrack">${state.goals.map(renderSlide).join('')}</div></div><nav class="viewer-nav" aria-label="Reisenavigation"><button class="nav-arrow prev" id="prevBtn" type="button" aria-label="Vorheriges Ziel">‹</button><button class="nav-arrow next" id="nextBtn" type="button" aria-label="Nächstes Ziel">›</button></nav><div class="counter-pill" id="counterPill">1 / ${state.goals.length}</div></section><div class="lightbox" id="lightbox" aria-hidden="true" role="dialog" aria-modal="true"><button class="lightbox-close" id="lightboxClose" type="button" aria-label="Foto schließen">×</button><img id="lightboxImage" alt="Vergrößertes Reisefoto"></div>`;bindViewerEvents();renderSlider(false);}
  function startJourney(){if(state.started)return;state.started=true;document.getElementById('introScreen')?.classList.add('hidden-view');document.getElementById('journeyScreen')?.classList.add('active');animateRoute();}
  function move(delta){const next=Math.max(0,Math.min(state.goals.length-1,state.current+delta));if(next===state.current)return;state.current=next;renderSlider(true);}
  function renderSlider(animate){const track=document.getElementById('sliderTrack');if(!track)return;track.style.transform=`translate3d(${-state.current*100}%,0,0)`;document.getElementById('prevBtn').hidden=state.current===0;document.getElementById('nextBtn').hidden=state.current===state.goals.length-1;document.getElementById('counterPill').textContent=`${state.current+1} / ${state.goals.length}`;if(animate)animateRoute();}
  function animateRoute(){const flare=document.querySelector(`.slide[data-index="${state.current}"] .route-flare`);if(!flare)return;flare.classList.remove('animate');void flare.offsetWidth;flare.classList.add('animate');}
  function openLightbox(index){const goal=state.goals[index];if(!goal)return;const image=document.getElementById('lightboxImage');image.src=goal.photo;image.alt=goal.name||`Ziel ${index+1}`;const box=document.getElementById('lightbox');box.classList.add('open');box.setAttribute('aria-hidden','false');}
  function closeLightbox(){const box=document.getElementById('lightbox');if(!box?.classList.contains('open'))return;box.classList.remove('open');box.setAttribute('aria-hidden','true');}
  function handleClick(event){if(event.target.closest('#startJourneyBtn')){startJourney();return;}if(event.target.closest('#prevBtn')){move(-1);return;}if(event.target.closest('#nextBtn')){move(1);return;}const photo=event.target.closest('[data-photo-index]');if(photo){openLightbox(Number(photo.dataset.photoIndex));return;}if(event.target.closest('#lightboxClose')||event.target.id==='lightbox')closeLightbox();}
  function handleKeydown(event){if(event.key==='Escape'){closeLightbox();return;}if(!state.started)return;if(event.key==='ArrowRight')move(1);if(event.key==='ArrowLeft')move(-1);}
  function pointerDown(event){if(!state.started||event.button>0)return;state.swipeStartX=event.clientX;state.swipeStartY=event.clientY;}
  function pointerUp(event){if(state.swipeStartX==null||state.swipeStartY==null)return;const dx=event.clientX-state.swipeStartX,dy=event.clientY-state.swipeStartY;state.swipeStartX=null;state.swipeStartY=null;if(Math.abs(dx)>=50&&Math.abs(dx)>Math.abs(dy))move(dx<0?1:-1);}
  function bindViewerEvents(){app.addEventListener('click',handleClick);window.addEventListener('keydown',handleKeydown);const viewport=document.getElementById('sliderViewport');viewport.addEventListener('pointerdown',pointerDown,{passive:true});viewport.addEventListener('pointerup',pointerUp,{passive:true});viewport.addEventListener('pointercancel',()=>{state.swipeStartX=null;state.swipeStartY=null;},{passive:true});}
  async function init(){setViewportSize();state.trip=await loadTrip();buildViewer();}
  window.addEventListener('resize',setViewportSize);window.visualViewport?.addEventListener('resize',setViewportSize);window.visualViewport?.addEventListener('scroll',setViewportSize);window.addEventListener('orientationchange',()=>setTimeout(setViewportSize,120));
  init().catch(error=>{console.error(error);showError(error.message||'Unbekannter Fehler.');});
})();
